"""empty message

Revision ID: 0186b6038227
Revises: 72807f1b017b
Create Date: 2024-04-25 20:37:00.796440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0186b6038227'
down_revision = '72807f1b017b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rtsp',
    sa.Column('rtspId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deviceCode', sa.String(length=50), nullable=True),
    sa.Column('deviceName', sa.String(length=50), nullable=True),
    sa.Column('rtsp_url', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rtspId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rtsp')
    # ### end Alembic commands ###
