"""empty message

Revision ID: 72807f1b017b
Revises: 
Create Date: 2024-03-25 22:21:07.154196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72807f1b017b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('organizationId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organizationName', sa.String(length=50), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.Column('deleteTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('organizationId')
    )
    op.create_table('rtsp',
    sa.Column('rtspId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deviceCode', sa.String(length=50), nullable=True),
    sa.Column('deviceName', sa.String(length=50), nullable=True),
    sa.Column('rtsp_url', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rtspId')
    )
    op.create_table('activation_code',
    sa.Column('activationCodeId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organizationId', sa.Integer(), nullable=False),
    sa.Column('activationCode', sa.String(length=50), nullable=True),
    sa.Column('isUsed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.organizationId'], ),
    sa.PrimaryKeyConstraint('activationCodeId')
    )
    op.create_table('admin',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('realName', sa.String(length=50), nullable=True),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True),
    sa.Column('organizationId', sa.Integer(), nullable=False),
    sa.Column('activationCode', sa.String(length=50), nullable=True),
    sa.Column('powerLevel', sa.Integer(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.Column('deleteTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.organizationId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('camera',
    sa.Column('cameraId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('organizationId', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.organizationId'], ),
    sa.PrimaryKeyConstraint('cameraId')
    )
    op.create_table('resident',
    sa.Column('nativeId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guardianId', sa.Integer(), nullable=True),
    sa.Column('nativename', sa.String(length=50), nullable=True),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('organizationId', sa.Integer(), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.Column('deleteTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.organizationId'], ),
    sa.PrimaryKeyConstraint('nativeId')
    )
    op.create_table('operation_record',
    sa.Column('recordId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('recordType', sa.String(length=50), nullable=True),
    sa.Column('nativeId', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nativeId'], ['resident.nativeId'], ),
    sa.ForeignKeyConstraint(['userId'], ['admin.userId'], ),
    sa.PrimaryKeyConstraint('recordId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_record')
    op.drop_table('resident')
    op.drop_table('camera')
    op.drop_table('admin')
    op.drop_table('activation_code')
    op.drop_table('rtsp')
    op.drop_table('organization')
    # ### end Alembic commands ###
